### ISSUE TITLE
Documentation after migration

### ISSUE THREAD

**Issue by ppxasjsm** [CCPBioSim/fesetup#10]
What happened to the wiki documentation since the migration?

**Comment by skfegan** [comment]
The documentation is being reformatted and (hopefully) improved and will be added to the website when it is ready.

**Comment by ppxasjsm** [comment]
Any timescale estimate on this?

**Comment by skfegan** [comment]
The documentation can be found at https://fesetup.readthedocs.io

**Comment by lohedges** [comment]
Thanks. It might be nice to link to the website in the GitHub README, or in the repo description. If you click on the "edit" button at the top right, where it says " A tool for setting up free energy simulations." you should be able to add a website link.
