### ISSUE TITLE
Ligand correct_for_pH

### ISSUE THREAD

**Issue by skfegan** [CCPBioSim/fesetup#13]
The options lig['correct_for_pH'] and lig['pH'] are not documented.

1. check how/if they work 
2. fix any bugs 
3. add documentation

**Comment by velocirraptor23** [comment]
It seems, there is the keyword in FESetup to setup pH for ligand but it seems desnt work. When I see the log file the pH for ligand is always 7.4. Is this meaningless term?

**Comment by skfegan** [comment]
The ligand correct_for_pH = true option also requires that add_hydrogens = true (add_hydrogens default is false). It will still need more testing.

**Comment by skfegan** [comment]
The ligand correct_for_pH and pH keywords work. Note: they are different to the propka and propka.pH keywords that are used for proteins. I would recommend that anyone using these keywords checks the output structures and charges to make sure they are suitable for the systems/conditions being studied.
