### ISSUE TITLE
Cofactors in FESetup

### ISSUE THREAD

**Issue by velocirraptor23** [CCPBioSim/fesetup#14]
Hi there,
I would like to setup a simulation with a ligand and a cofactor. Is it possible with FESetup?

Bests

Cesar

**Comment by skfegan** [comment]
Hi,

Yes, it is possible to setup a simulation with a cofactor. You would include the cofactor with the protein.

The FESetup users list can be subscribed to at: 
https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=CCPBIOSIM-FESETUP 

Best wishes,
Sarah
