### ISSUE TITLE
update for newer ambertools?

### ISSUE THREAD

**Issue by HCl0906** [CCPBioSim/fesetup#17]
Hi,
It's a very useful tool! While the internal ambertools16 is somewhat old.
How can I use it with newer amertools?
I installed the tool using executable file from http://www.ccpbiosim.ac.uk/software.
I also noticed this [https://github.com/CCPBioSim/fesetup/issues/5], and tried to modify the installed package.
While it doesn't work, and errior dettails are as follows:

```
`Making biomolecule rec...
ERROR: rec failed: Leap did not create the topology and/or coordinate file(s): vacuum.parm7, vacuum.rst7
Making ligand lig1...
IOError: [Errno 2] No such file or directory: 'sqm.out'
`
```

Could someone give me a brief guidance?

**Comment by skfegan** [comment]
You are going to have to do a bit of digging to figure out why it failed. What are the errors in the leap.log file (in _protein/rec)? Also, the .log file (in the directory where you ran FESetup) will probably contain some more information about what is happening.

**Comment by HCl0906** [comment]
> You are going to have to do a bit of digging to figure out why it failed. What are the errors in the leap.log file (in _protein/rec)? Also, the .log file (in the directory where you ran FESetup) will probably contain some more information about what is happening.

Thanks. I have tried to fix an error, but there is new error. following is error detail from .log file: 
```
  stderr {
    /home/hcl/FESetup1.2.1/FESetup64/amber18/bin/to_be_dispatched/antechamber: Fatal Error!
    Weird atomic valence (1) for atom (ID: 2, Name: C2).
           Possible open valence.
  }
```

While my input structure should be OK. and there is no error when I use the internal amber16.
I will use the internal amber16 & thanks again.

**Comment by skfegan** [comment]
Hi, the possible open valence error comes from the acdoctor part antechamber (on by default from Amber 18, a separate program in Amber 16). If you add the "-dr no" flag to the antechamber command that should remove the error with amber18 (but will cause an error for amber16). However if you make this change you must check your output structures to make sure they are ok (always a good idea in any case).

**Comment by HCl0906** [comment]
Thanks a lot. It works! And the output structure seems OK (not quite sure).
By the way, it also works for ambertools19.
