### ISSUE TITLE
Perturbation part of https://training.ccpbiosim.ac.uk/fesetup-workshop/ not working for me

### ISSUE THREAD

**Issue by waydeveldman** [CCPBioSim/fesetup#19]
Good day! I hope you're well.

Everything worked for me, up until the perturbations when I run morph.in. PLEASE HELP!
I am getting the following, in the terminal and leap.log file:

Terminal:
Making biomolecule 181L...
Morphs will be generated for Sire
Morphing benzene to o-xylene...
ERROR: benzeneo-xylene failed: Leap did not create the topology and/or coordinate file(s): vacuum.parm7, vacuum.rst7
Morphing o-xylene to benzene...
Creating complex 181L:benzene with ligand morph benzeneo-xylene...
AttributeError: 'NoneType' object has no attribute 'edit'

leap.log:

    s = combine {cmp0}
    Sequence: LIG
    saveAmberParm s "state0.parm7" "state0.rst7"
    Checking Unit.
    Building topology.
    Building atom parameters.
    For atom: .R<LIG 1>.A<DU13 13> Could not find vdW (or other) parameters for type: du
    For atom: .R<LIG 1>.A<DU14 14> Could not find vdW (or other) parameters for type: du
    For atom: .R<LIG 1>.A<DU15 15> Could not find vdW (or other) parameters for type: du
    For atom: .R<LIG 1>.A<DU16 16> Could not find vdW (or other) parameters for type: du
    For atom: .R<LIG 1>.A<DU17 17> Could not find vdW (or other) parameters for type: du
    For atom: .R<LIG 1>.A<DU18 18> Could not find vdW (or other) parameters for type: du
    Parameter file was not saved.
    savepdb s "state0.pdb"
    Writing pdb file: state0.pdb
    quit
    Quit

**Comment by skfegan** [comment]
This is a copy of the issue in the workshop repository.
