### ISSUE TITLE
MacOS Installation 

### ISSUE THREAD

**Issue by MKCarter** [CCPBioSim/fesetup#20]
Hi, I am running a Mac and have been trying to install FESetup from the downloadable shell script from https://www.ccpbiosim.ac.uk/software

When running the script it errors due to my Mac OS:

`Installing package FESetup release 1.2.1...

Determining system environment...
ERROR: unsupported operating system: Darwin.
Aborting the installation of FESetup release 1.2.1!`

I am guessing the shell script works only for Linux and not MacOS. Are there any plans to release a Mac compatible version anytime soon?

Thanks

**Comment by skfegan** [comment]
There are no plans to make a Mac compatible version. I am not a Mac user or owner (and I don't think work will buy a Mac just for this project).
